@Backend_HostAddress = http://localhost:5187

### Health / állapot
GET {{Backend_HostAddress}}/api/health
Accept: application/json

###

### Feladatok listázása (lapozva)
GET {{Backend_HostAddress}}/api/todos?page=1&pageSize=5
Accept: application/json

###

### Új feladat létrehozása
POST {{Backend_HostAddress}}/api/todos
Content-Type: application/json

{
	"title": "Határidős munka",
	"description": "Leadandó feladat elkészítése a határidő előtt",
	"isCompleted": false,
	"dueAt": null
}

###

### Feladat lekérése azonosító alapján
@TodoId = REPLACE_WITH_ID
GET {{Backend_HostAddress}}/api/todos/{{TodoId}}
Accept: application/json

###

### Feladat frissítése (teljes csere / PUT)
PUT {{Backend_HostAddress}}/api/todos/{{TodoId}}
Content-Type: application/json

{
	"title": "Határidős munka (frissítve)",
	"description": "Utolsó ellenőrzés, feltöltés / leadás",
	"isCompleted": false,
	"dueAt": null
}

###

### Feladat törlése
DELETE {{Backend_HostAddress}}/api/todos/{{TodoId}}
