@Backend_HostAddress = http://localhost:5187

### Health
GET {{Backend_HostAddress}}/api/health
Accept: application/json

###

### List todos (paged)
GET {{Backend_HostAddress}}/api/todos?page=1&pageSize=5
Accept: application/json

###

### Create todo
POST {{Backend_HostAddress}}/api/todos
Content-Type: application/json

{
	"title": "Bevásárlás",
	"description": "tej, kenyér, tojás",
	"isCompleted": false,
	"dueAt": null
}

###

### Get todo by id
@TodoId = REPLACE_WITH_ID
GET {{Backend_HostAddress}}/api/todos/{{TodoId}}
Accept: application/json

###

### Update todo (replace)
PUT {{Backend_HostAddress}}/api/todos/{{TodoId}}
Content-Type: application/json

{
	"title": "Bevásárlás (frissítve)",
	"description": "tej, kenyér, tojás, alma",
	"isCompleted": false,
	"dueAt": null
}

###

### Delete todo
DELETE {{Backend_HostAddress}}/api/todos/{{TodoId}}
